site_name: GFGM
site_url: https://www.gfgm.de/
nav:
  - Home: index.md
  - About: 
    - 'Privacy': 'privacy.md'
theme:
  name: 'material'
  #custom_dir: overrides
  palette:
    primary: white
    accent: deep blue


plugins:
  - search
  - mermaid2
  - mkdocs-video
  - awesome-pages
  - blogging:
      dirs: 
       - guides
      features:
        tags: {}
      paging: true
      sort:
        from: new
      size: 10
      locale: en         # The locale for time localizations, default: system's locale
      time_format: '%Y-%m-%d %H:%M:%S' # The format used to display the time
      meta_time_format: '%Y-%m-%d %H:%M:%S' # The format used to parse the time from meta
  - tags
  - privacy
  - rss:
      match_path: docs/guides/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - social

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - attr_list
  - def_list
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
    - accept
    - manage
    generator: false # hide the line "Made with Material for MkDocs"

copyright: Copyright &copy; 2024 GFGM