site_name: GFGM
site_url: https://www.gfgm.de/
nav:
  - Home: index.md
  - Tags: tags.md
  - About: 
    - 'Privacy': 'privacy.md'
theme:
  name: 'material'
  #custom_dir: overrides
  palette:
    - primary: red
      accent: blue
      scheme: default
      toggle:
       icon: material/weather-night
       name: Switch to dark mode    
    - primary: black
      accent: red
      scheme: slate
      toggle:
       icon: material/brightness-7
       name: Switch to light mode


plugins:
  - search
  - mermaid2
  - mkdocs-video
  - awesome-pages
  - blog:
     blog_dir: blog
     blog_toc: true
     authors_profiles: true
  - tags
  - privacy
  - rss:
      match_path: docs/guides/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - social

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - attr_list
  - def_list
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
    - accept
    - manage
    generator: false # hide the line "Made with Material for MkDocs"
extra_css:
 - stylesheets/extra.css

copyright: Copyright &copy; 2024 GFGM

