authors:
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  agaertne:
    name: Andreas Gärtner
    description: IT
    avatar: https://picsum.photos/536/354